---
## Dwl_Stack compose file
version: "3.8"

networks:

  vpn_network:
    external: true
    name: vpn_network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24    # docker network create --driver=bridge --subnet=172.20.0.0/24 vpn_network

services:

  wireguard:
    image: lscr.io/linuxserver/wireguard:${WG_TAG:-latest}
    container_name: wireguard
    restart: unless-stopped
    environment:
      PUID: ${XID:-0}
      PGID: ${XID:-0}
      TZ: ${TZ:-Europe/Paris}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      vpn_network:
        ipv4_address: 172.20.0.200

  plex:
    image: lscr.io/linuxserver/plex:${PLEX_TAG:-latest}
    container_name: plex
    restart: unless-stopped
    environment:
      PUID: ${XID:-0}
      PGID: ${XID:-0}
      TZ: ${TZ:-Europe/Paris}
      UMASK: 0002
      VERSION: docker
    expose:
      - 32400
    volumes:
      - ./config/plex:/config
      - ./scripts/custom-cont-init.d:/custom-cont-init.d
      - ./path/to/tvseries:/tv
      - ./path/to/movies:/movies
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.plex.rule=Host(`plex.${DOMAINE:?err}`)"
    #   - "traefik.http.routers.plex.entrypoints=web,websecure"
    #   - "traefik.http.routers.plex.tls=true"
    #   - "traefik.http.routers.plex.tls.certresolver=cf"
    #   - "traefik.http.routers.plex.service=plex-svc"
    #   - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
    #   - "traefik.http.routers.plex.middlewares=auth_2FA@file"
    networks:
      vpn_network:
        ipv4_address: 172.20.0.10
...
