site_name: Plex Wireguard Stack
site_url: https://limedrive.github.io/plex_wg_stack/
repo_url: https://github.com/LimeDrive/plex_wg_stack
repo_name: LimeDrive/plex_wg_stack

nav:
  - Home: index.md
  - Tutorials:
    - Gluetun:
      - Fix for SSDV2: gluetun/gluetun_plex_install_ssdv2.md
    - Wireguard:

theme:
  icon:
    repo: fontawesome/brands/github 
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal
      accent: lime

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: lime
