site_name: Plex Wireguard Stack
site_url: https://limedrive.github.io/plex_wg_stack/
repo_url: https://github.com/LimeDrive/plex_wg_stack
repo_name: LimeDrive/plex_wg_stack

nav:
  - Home: index.md
  - Tutorials:
      - Fix for SSDV2: gluetun/gluetun_plex_install_ssdv2.md
      - VPS Setup: wg-stack/install_server_vps.md

theme:
  icon:
    repo: fontawesome/brands/github 
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal
      accent: lime

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: lime
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details