name: master

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up the environment
      uses: ./.github/actions/setup-poetry-env

    - name: Check if documentation can be built
      run: poetry run mkdocs build -s